//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by plugindialogs.rc
//
#define IDC_RAW_BUTTON_ADD_RAW_EXTENSION 1100
#define IDC_RAW_BUTTON_ADDCAMERA        1101
#define IDC_RAW_BUTTON_APPLY            1102
#define IDC_RAW_BUTTON_BADPIXELS        1103
#define IDC_RAW_BUTTON_BADPIXELSHELP    1104
#define IDC_RAW_BUTTON_CAM_ICC          1105
#define IDC_RAW_BUTTON_COPY             1106
#define IDC_RAW_BUTTON_DEBUGCMD         1107
#define IDC_RAW_BUTTON_DEFAULTS         1108
#define IDC_RAW_BUTTON_OUT_ICC          1109
#define IDC_RAW_BUTTON_PASTE            1110
#define IDC_RAW_BUTTON_REMOVE_RAW_EXTENSION 1111
#define IDC_RAW_BUTTON_REMOVECAMERA     1112
#define IDC_RAW_CHECK_BADPIXELS         1113
#define IDC_RAW_CHECK_CORRECTGEOMETRY   1114
#define IDC_RAW_CHECK_DCRAW             1115
#define IDC_RAW_CHECK_FIXEDWHITELEVEL   1116
#define IDC_RAW_CHECK_MEDIAN            1117
#define IDC_RAW_CHECK_NOISETHRESHOLD    1118
#define IDC_RAW_CHECK_PNM               1119
#define IDC_RAW_CHECK_RGBASFOUR         1120
#define IDC_RAW_COMBO_CAM_ICC           1121
#define IDC_RAW_COMBO_DISPLAYEDIMAGE    1122
#define IDC_RAW_COMBO_GAMMA             1123
#define IDC_RAW_COMBO_HIGHLIGHTMODE     1124
#define IDC_RAW_COMBO_INTERPQUALITY     1125
#define IDC_RAW_COMBO_OUT_ICC           1126
#define IDC_RAW_COMBO_ROTATION          1127
#define IDC_RAW_COMBO_WHITEBALANCE      1128
#define IDC_RAW_EDIT_BADPIXELS          1129
#define IDC_RAW_EDIT_BRIGHTNESS         1130
#define IDC_RAW_EDIT_CAM_ICC            1131
#define IDC_RAW_EDIT_CHROMA_BLUE        1132
#define IDC_RAW_EDIT_CHROMA_RED         1133
#define IDC_RAW_EDIT_GAMMA_POWER        1134
#define IDC_RAW_EDIT_GAMMA_TOESLOPE     1135
#define IDC_RAW_EDIT_MEDIAN             1136
#define IDC_RAW_EDIT_NOISETHRESHOLD     1137
#define IDC_RAW_EDIT_OUT_ICC            1138
#define IDC_RAW_EDIT_RAW_EXTENSION      1139
#define IDC_RAW_EDIT_USERMUL_1          1140
#define IDC_RAW_EDIT_USERMUL_2          1141
#define IDC_RAW_EDIT_USERMUL_3          1142
#define IDC_RAW_EDIT_USERMUL_4          1143
#define IDC_RAW_LIST_CAMERAS            1144
#define IDC_RAW_LIST_RAW_EXTENSIONS     1145
#define IDC_RAW_LIST_SUPCAMS            1146
#define IDC_RAW_RICHEDIT_CREDITS        1147
#define IDC_RAW_SPIN_BRIGHTNESS         1148
#define IDC_RAW_SPIN_CHROMA_BLUE        1149
#define IDC_RAW_SPIN_CHROMA_RED         1150
#define IDC_RAW_SPIN_GAMMA_POWER        1151
#define IDC_RAW_SPIN_GAMMA_TOESLOPE     1152
#define IDC_RAW_SPIN_MEDIAN             1153
#define IDC_RAW_SPIN_NOISETHRESHOLD     1154
#define IDC_RAW_SPIN_USERMUL_1          1155
#define IDC_RAW_SPIN_USERMUL_2          1156
#define IDC_RAW_SPIN_USERMUL_3          1157
#define IDC_RAW_SPIN_USERMUL_4          1158
#define IDC_RAW_STATIC_BRIGHTNESS       1159
#define IDC_RAW_STATIC_CAM_ICC          1160
#define IDC_RAW_STATIC_CAMERA_NAME_HEADING 1161
#define IDC_RAW_STATIC_CAMERAS          1162
#define IDC_RAW_STATIC_CHROMA           1163
#define IDC_RAW_STATIC_CHROMA_BLUE      1164
#define IDC_RAW_STATIC_CHROMA_RED       1165
#define IDC_RAW_STATIC_DISPLAYEDIMAGE   1166
#define IDC_RAW_STATIC_FILTERS          1167
#define IDC_RAW_STATIC_GAMMA            1168
#define IDC_RAW_STATIC_GAMMA_POWER      1169
#define IDC_RAW_STATIC_GAMMA_TOESLOPE   1170
#define IDC_RAW_STATIC_HIGHLIGHTMODE    1171
#define IDC_RAW_STATIC_INTERPQUALITY    1172
#define IDC_RAW_STATIC_MEDIAN_PASSES    1173
#define IDC_RAW_STATIC_OUT_ICC          1174
#define IDC_RAW_STATIC_RAW_EXTENSIONS   1175
#define IDC_RAW_STATIC_ROTATION         1176
#define IDC_RAW_STATIC_WHITEBALANCE     1177
#define IDC_RAW_TAB                     1178
#define IDC_RAW_STATIC_SUPCAMS          1179
#define IDD_RAW_CONFIG                  2365
#define IDD_RAW_DCRAW                   2366
#define IDD_RAW_FORMATS                 2367

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1200
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
